### ISSUE TITLE
launch image

### ISSUE THREAD

**Issue by dothework** [dothework/alexa-skill-today-andorid#13]
two things about the launch image. 

1. there is an all white screen that shows initially and is shown (on my simulator) for 2-3 seconds before the launch image. is there not a way to have the white screen be the launch image? there must be.

2. the launch images is not sized properly for the device I'm on (in the simulator). is this as simple as getting more screen launch images sizes?

**Comment by halfjew22** [comment]
That definitely started to catch my eye as well. I'm looking into ways to
fix that.

The sizings for the launch image seemed strange, but I'll try and make them
work properly.

**Comment by dothework** [comment]
potentially useful article [https://www.bignerdranch.com/blog/splash-screens-the-right-way/](https://www.bignerdranch.com/blog/splash-screens-the-right-way/)

**Comment by dothework** [comment]
we can ask Simon to create any sized image we need - and that is probably best as he'd tweak them to perfection.

**Comment by halfjew22** [comment]
That's the guide I'm going to try first! Seems baking it into the theme is
the way to go rather than waiting for view inflation. The more you know!

**Comment by halfjew22** [comment]
Additionally, do you just want to use the same card layout for your podcast
that we use for a skill?

**Comment by dothework** [comment]
Yes, same layout.

**Comment by halfjew22** [comment]
I think it would be more performant if Simon could provide
