### ISSUE TITLE
veritcal spacing between itmes

### ISSUE THREAD

**Issue by dothework** [dothework/alexa-skill-today-andorid#14]
while it wasn't called out in Simon's documents, there are material design standards that aren't in being followed. 

references for this topic: 

- [https://material.google.com/layout/metrics-keylines.html](https://material.google.com/layout/metrics-keylines.html)

- [https://material.google.com/style/typography.html#typography-styles](https://material.google.com/style/typography.html#typography-styles)

**Comment by halfjew22** [comment]
Mark, could you please call out the specific dimensions you'd like for
unsatisfactory visuals?

**Comment by dothework** [comment]
Yes. Is this guide enough? 

![screen shot 2016-06-26 at 10 26 16 am](https://cloud.githubusercontent.com/assets/9028552/16362906/9cf627bc-3b88-11e6-9913-088644cb5676.png)

**Comment by halfjew22** [comment]
Could you please specifically call out the elements in our app that you
aren't satisfied with as well as the exact dimensions (in sp) that you
would like them to be?

**Comment by dothework** [comment]
distance between the skill title and app publisher name

**Comment by halfjew22** [comment]
And the value in DP you would like that to be?

**Comment by dothework** [comment]
32

**Comment by halfjew22** [comment]
Mark, 32dp is WAY too much space between these two texts. Here's what that looks like below. The type still aligns to the 4dp grid, there just needs to be less distance vertically between the two as the are title / subtitle. 

![screenshot 2016-06-26 13 10 43](https://cloud.githubusercontent.com/assets/6922904/16364592/f972b1ba-3b9f-11e6-92ce-2caac0e683cc.png)

**Comment by halfjew22** [comment]
Here's the most pertinent bit of material design keylining for our purposes.

![](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3bElRc0xaZGR4S0E/components_cards20.png)

**Comment by halfjew22** [comment]
Notice they don't even mentioned the margin between Title goes here and Subtitle here. Just eyeballing it, that's our 8dp that we currently have, and it doesn't appear anything needs to be changed.

**Comment by dothework** [comment]
Make it 5. 






On Sun, Jun 26, 2016 at 4:16 PM -0400, "Michael Lustig" <notifications@github.com> wrote:












Notice they don't even mentioned the margin between Title goes here and Subtitle here. Just eyeballing it, that's our 8dp that we currently have, and it doesn't appear anything needs to be changed.

**Comment by halfjew22** [comment]
5 would break the 4 dp guideline. 4 or 5 final answer?

**Comment by dothework** [comment]
let's try 4 then. 8 is way to much.

**Comment by halfjew22** [comment]
Agreed, how's this?

![screenshot_20160626-133642](https://cloud.githubusercontent.com/assets/6922904/16364724/1a0eaeee-3ba3-11e6-9440-41b51b652a2d.png)

**Comment by dothework** [comment]
looks spot on.

**Comment by halfjew22** [comment]
Then I believe we are done! Sending you APK now.

**Comment by dothework** [comment]
👏
