### ISSUE TITLE
second card/podcast promo

### ISSUE THREAD

**Issue by dothework** [dothework/alexa-skill-today-andorid#17]
please read the "show" element in the "cardAd" element of the firebase and show the mic icon accordingly.

be sure to make the text of the button on this card pull from Remote Config `podcast_card_button_label`  OR? should it pull from an element in the "cardAd"?

can you also modify the icon shown on the overflow to be indicated in a Remote Config?

**Comment by halfjew22** [comment]
Mark, you had told me a couple days ago to hold off on (and remove) this
second card. Now there is an issue to put it back. I'm happy to have this
card or not but I'd really appreciate a lock on these features as I'm sure
you can understand. Is this the last additional feature that will be added
before we trigger our initial payment?

**Comment by halfjew22** [comment]
Please address this before I get to work today.

**Comment by dothework** [comment]
Fair. Let's table the second card. Let's also push out a beta and get some feedback before we call it complete. We'll only fix issues though, nothing new.

**Comment by halfjew22** [comment]
Sounds great! Thanks for understanding. Closed for now. Please assign to a separate milestone if you'd like.
