### ISSUE TITLE
beta version for play distribution

### ISSUE THREAD

**Issue by dothework** [dothework/alexa-skill-today-andorid#18]
please prepare a beta version for the google play store. the current version will not work because debugging is enabled. 

also disable the long tap on the share button.

**Comment by halfjew22** [comment]
https://www.dropbox.com/s/0h100hnro90f7ac/asotd-v1.0.0-release.apk?dl=0

**Comment by dothework** [comment]
do you have the ability to grab screen shots from your device - that we can use in the store listing? if that's easy (it is on iOS) then please grab today's screen shot and also the alexa app showing that app detail page. LMK.

**Comment by halfjew22** [comment]
Not sure we should show the Alexa App Detail page for copyright purposes unless you can get (and prove) that Amazon are okay with that. Google can be finicky with removals for those kinds of reasons. 

Grabbing now.

**Comment by dothework** [comment]
I'm unlikely to get amazon to approve. let's skip that. good call. we need two screen shots though. so let's also grab the 1-Minute Mindfulness skill.

**Comment by halfjew22** [comment]
https://www.dropbox.com/s/sger35u4l32dssn/Alexa%20Skills%20Screenshots.zip?dl=0

**Comment by dothework** [comment]
is this expected on the emulator? 
![screen shot 2016-06-26 at 5 27 14 pm](https://cloud.githubusercontent.com/assets/9028552/16365063/56217ec8-3bc3-11e6-8eb1-71a47ec4c304.png)

**Comment by halfjew22** [comment]
The very first time you try and install from the debug version to
production version, yes. Uninstall debug and then drag the production build
into emulator. Error will go away.

**Comment by dothework** [comment]
that worked. lovely, absolutely lovely launch sequence. awesome.

**Comment by halfjew22** [comment]
Really was quite brilliant. We make a great team Mark.
