### ISSUE TITLE
Implement final designs

### ISSUE THREAD

**Issue by halfjew22** [dothework/alexa-skill-today-andorid#3]

**Comment by halfjew22** [comment]
Just made a small change to have the card scroll and wrap the entire content. Waiting on final design's from the british man.

**Comment by dothework** [comment]
The border on the bottom of the card is missing. Perhaps this is only on the emulator (but that seems unlikely - the purpose of the emulator is to provide a realistic experience after all). See this image. The border must be visible and implemented to the material design spec. 
![screen shot 2016-06-23 at 10 51 08 am](https://cloud.githubusercontent.com/assets/9028552/16307821/ac082f5c-3930-11e6-91ba-318bb44e0ebe.png)

**Comment by dothework** [comment]
assets have arrived. please note anything missing and we'll get it sorted out asap.

[https://www.dropbox.com/sh/qjdqerp3jwx2jln/AAAkwMgJgWOiRUYA6SeI7k-da?dl=0](https://www.dropbox.com/sh/qjdqerp3jwx2jln/AAAkwMgJgWOiRUYA6SeI7k-da?dl=0)

**Comment by halfjew22** [comment]
UU lala. I love those assets and this guy is very detailed. I'm going to have to retract my statement about the timeliness. Stuff comes up. I should be able to knock out a chunk of this tonight. Will let you know.

**Comment by halfjew22** [comment]
Now, hero images are included in the Dropbox dump. Do you want to ship those with the app or are you putting them on Firebase?

**Comment by dothework** [comment]
Already in firebase storage and in the data too. 






On Fri, Jun 24, 2016 at 9:49 PM -0400, "Michael Lustig" <notifications@github.com> wrote:












Now, hero images are included in the Dropbox dump. Do you want to ship those with the app or are you putting them on Firebase?

**Comment by halfjew22** [comment]
What exactly do you want me to do with the StartupScreen folder? There's two different screens there. Not sure which one to use.

**Comment by dothework** [comment]
Either combine them into a single image, or animate them if it's simply accomplished. 






On Fri, Jun 24, 2016 at 9:52 PM -0400, "Michael Lustig" <notifications@github.com> wrote:












What exactly do you want me to do with the StartupScreen folder? There's two different screens there. Not sure which one to use.

**Comment by halfjew22** [comment]
Card cutoff is fixed.
