### ISSUE TITLE
Add Deeplink to specific publisher

### ISSUE THREAD

**Issue by halfjew22** [dothework/alexa-skill-today-andorid#6]

**Comment by halfjew22** [comment]
We need to determine an encoding to use on our deep links. Somehow, what's in the URL has to get translated into a unique key for a specific publisher's piece of content. Right now, I just use string compare but that absolutely won't scale. 

@dothework I need you to brainstorm how we'd like to do this.

**Comment by dothework** [comment]
modify the domain used in the deep links to talkingalexa.com or app.talkingalexa.com - the firebase web app is at app.talkingalexa.com. talkingalexa.com is a WordPress site. 

I've added a new entry to the JSON for each day's skill. deepLinkID - it's a random string.

**Comment by halfjew22** [comment]
Mark, you'll have to create deep links on Firebase with the appropriate random string for these to work properly. I'll set up the functionality and the pattern to work for a couple of them right now.
