### ISSUE TITLE
Makes sense to me to just have the content expanded already

### ISSUE THREAD

**Issue by halfjew22** [dothework/alexa-skill-today-andorid#7]
No need to have the user required to click a button to show content. At the most, we should have the content scroll under the Skill's illustration to read the entire description.

**Comment by dothework** [comment]
Is it normal, typical or standard to have content on a card that scrolls? Or should the card be enlarged so that the card itself scrolls in its' container? I don't know the standards here.

**Comment by halfjew22** [comment]
I'll look up the material guideline and get back to you. My gut tells me we
should have the cards entire content scroll up and down "underneath" the
image. Image stationary content scrolls. I'll check.

Is it normal, typical or standard to have content on a card that scrolls?
Or should the card be enlarged so that the card itself scrolls in its'
container? I don't know the standards here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dothework/alexa-skill-today-andorid/issues/7#issuecomment-225571360>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGmimI8qaCcGUiEscfrrjeLH-am0KXXQks5qLVHggaJpZM4Iz-Ot>
.

**Comment by dothework** [comment]
have the content fully expanded. The card will have to grow to contain it - or shrink.  

do have the cards scroll under the title bar/menu bar - the top image is part of the card
