### ISSUE TITLE
Mark, I've set up the issue tracker. Let's make this the source of truth.

### ISSUE THREAD

**Issue by halfjew22** [dothework/alexa-skill-today-andorid#8]
Please verify these issues that I've listed below and add any more that you're going to require to reach our minimum viable product. We want to get something very functional working, but not go on a wild goose chase and suffer from feature creep. Later on down the road, we can talk about iterating, but I'd like to set up a source of truth that we can go off of to determine when I am "finished" with v1.

@dothework Please read the above, perform those actions, and mark this completed when you are through.

**Comment by dothework** [comment]
@halfjew22 I'll work through these issues and add any others needed over the course of the day.

**Comment by halfjew22** [comment]
Wonderful. Thank you Mark.
